FROM node:8.5.0

WORKDIR /app/
COPY .babelrc /app/.babelrc
COPY .soliumrc.json /app/.soliumrc.json
COPY .soliumignore /app/.soliumignore
COPY .eslintrc.js /app/.eslintrc.js
COPY package.json /app/package.json
COPY contracts /app/contracts
COPY installed_contracts /app/installed_contracts
COPY test /app/test
COPY utils /app/utils
COPY migrations /app/migrations
COPY truffle.js /app/truffle.js

RUN npm install --only=production
RUN npm run compile
