profile = { default = { libs = ["node_modules", "lib"] } }
[default]
src = 'src'
out = 'foundry_artifacts'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'sol-explore/=node_modules/sol-explore/',
    'ds-test/=lib/ds-test/src/',
    'contracts/=contracts/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config