name: Analyze
on:
  pull_request:
  push:
    branches:
      - confluence
      - next

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Needed for commands that depend on git tags
          fetch-depth: 0
      - name: Install dependencies
        run: |
          yarn
      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          sarif: results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
