name: Build
on:
  pull_request:
  push:
    branches:
      - confluence
      - cf/next

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Needed for commands that depend on git tags
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn --immutable
      - name: Linter
        run: |
          yarn lint
      - name: Compile contracts
        run: |
          yarn compile
      - name: 💡 Run contract tests with coverage reporting
        run: |
          yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
