name: Git Checks

on: [push]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    steps:
        # https://github.com/actions/checkout/releases/tag/v2.0.0
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
      - name: Block Fixup Commit Merge
        # https://github.com/13rac1/block-fixup-merge-action/releases/tag/v1.1.1
        uses: 13rac1/block-fixup-merge-action@a82405273693189df42d8aba5f3d0553d2dc77f2
