name: Run test suite for the project

on:
  pull_request:
  push:
    branches:
      - delta
      - confluence
      - streamflow
      - next
      - master

jobs:
  test:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Compile contracts
        run: yarn compile

      - name: 💡 Run contract tests with coverage reporting
        run: yarn test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          files: ./coverage/lcov.info
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.CI_CODECOV_TOKEN }}

      - name: Enforce test coverage threshold
        run: yarn test:coverage:check

  editorconfig:
    name: Run editorconfig checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@7b3ae4aa4c2245e1296bfeb7690729093697f5b3 # v2.3.0

      - name: Run editorconfig checker against the repo
        run: editorconfig-checker
